/**
 * Gateway Software API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GatewaySoftwareApi);
  }
}(this, function(expect, GatewaySoftwareApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GatewaySoftwareApi.ActionsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ActionsApi', function() {
    describe('actionsDelete', function() {
      it('should call actionsDelete successfully', function(done) {
        //uncomment below and update the code to test actionsDelete
        //instance.actionsDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('actionsExecute', function() {
      it('should call actionsExecute successfully', function(done) {
        //uncomment below and update the code to test actionsExecute
        //instance.actionsExecute(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('actionsGet', function() {
      it('should call actionsGet successfully', function(done) {
        //uncomment below and update the code to test actionsGet
        //instance.actionsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('actionsGetAction', function() {
      it('should call actionsGetAction successfully', function(done) {
        //uncomment below and update the code to test actionsGetAction
        //instance.actionsGetAction(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('actionsGetEvents', function() {
      it('should call actionsGetEvents successfully', function(done) {
        //uncomment below and update the code to test actionsGetEvents
        //instance.actionsGetEvents(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('actionsPost', function() {
      it('should call actionsPost successfully', function(done) {
        //uncomment below and update the code to test actionsPost
        //instance.actionsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('actionsPut', function() {
      it('should call actionsPut successfully', function(done) {
        //uncomment below and update the code to test actionsPut
        //instance.actionsPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
