/**
 * Gateway Software API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GatewaySoftwareApi);
  }
}(this, function(expect, GatewaySoftwareApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GatewaySoftwareApi.DashboardsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DashboardsApi', function() {
    describe('dashboardsGetDeviceStatusByDeviceType', function() {
      it('should call dashboardsGetDeviceStatusByDeviceType successfully', function(done) {
        //uncomment below and update the code to test dashboardsGetDeviceStatusByDeviceType
        //instance.dashboardsGetDeviceStatusByDeviceType(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('dashboardsGetDeviceStatusByNetworkSwitch', function() {
      it('should call dashboardsGetDeviceStatusByNetworkSwitch successfully', function(done) {
        //uncomment below and update the code to test dashboardsGetDeviceStatusByNetworkSwitch
        //instance.dashboardsGetDeviceStatusByNetworkSwitch(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('dashboardsGetDeviceStatusBySpace', function() {
      it('should call dashboardsGetDeviceStatusBySpace successfully', function(done) {
        //uncomment below and update the code to test dashboardsGetDeviceStatusBySpace
        //instance.dashboardsGetDeviceStatusBySpace(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
