/**
 * Gateway Software API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GatewaySoftwareApi);
  }
}(this, function(expect, GatewaySoftwareApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GatewaySoftwareApi.DevicesApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DevicesApi', function() {
    describe('devicesAll', function() {
      it('should call devicesAll successfully', function(done) {
        //uncomment below and update the code to test devicesAll
        //instance.devicesAll(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('devicesDeleteAll', function() {
      it('should call devicesDeleteAll successfully', function(done) {
        //uncomment below and update the code to test devicesDeleteAll
        //instance.devicesDeleteAll(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('devicesDiscover', function() {
      it('should call devicesDiscover successfully', function(done) {
        //uncomment below and update the code to test devicesDiscover
        //instance.devicesDiscover(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('devicesGetNode', function() {
      it('should call devicesGetNode successfully', function(done) {
        //uncomment below and update the code to test devicesGetNode
        //instance.devicesGetNode(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('devicesGetSpace', function() {
      it('should call devicesGetSpace successfully', function(done) {
        //uncomment below and update the code to test devicesGetSpace
        //instance.devicesGetSpace(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('devicesPut', function() {
      it('should call devicesPut successfully', function(done) {
        //uncomment below and update the code to test devicesPut
        //instance.devicesPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('devicesSearch', function() {
      it('should call devicesSearch successfully', function(done) {
        //uncomment below and update the code to test devicesSearch
        //instance.devicesSearch(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('devicesUnassigned', function() {
      it('should call devicesUnassigned successfully', function(done) {
        //uncomment below and update the code to test devicesUnassigned
        //instance.devicesUnassigned(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
