/**
 * Gateway Software API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GatewaySoftwareApi);
  }
}(this, function(expect, GatewaySoftwareApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GatewaySoftwareApi.DimmersApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DimmersApi', function() {
    describe('dimmersDelete', function() {
      it('should call dimmersDelete successfully', function(done) {
        //uncomment below and update the code to test dimmersDelete
        //instance.dimmersDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('dimmersDiscover', function() {
      it('should call dimmersDiscover successfully', function(done) {
        //uncomment below and update the code to test dimmersDiscover
        //instance.dimmersDiscover(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('dimmersEventPost', function() {
      it('should call dimmersEventPost successfully', function(done) {
        //uncomment below and update the code to test dimmersEventPost
        //instance.dimmersEventPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('dimmersGet', function() {
      it('should call dimmersGet successfully', function(done) {
        //uncomment below and update the code to test dimmersGet
        //instance.dimmersGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('dimmersGetDimmer', function() {
      it('should call dimmersGetDimmer successfully', function(done) {
        //uncomment below and update the code to test dimmersGetDimmer
        //instance.dimmersGetDimmer(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('dimmersGetEvents', function() {
      it('should call dimmersGetEvents successfully', function(done) {
        //uncomment below and update the code to test dimmersGetEvents
        //instance.dimmersGetEvents(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('dimmersPost', function() {
      it('should call dimmersPost successfully', function(done) {
        //uncomment below and update the code to test dimmersPost
        //instance.dimmersPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('dimmersPut', function() {
      it('should call dimmersPut successfully', function(done) {
        //uncomment below and update the code to test dimmersPut
        //instance.dimmersPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
