/**
 * Gateway Software API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GatewaySoftwareApi);
  }
}(this, function(expect, GatewaySoftwareApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GatewaySoftwareApi.LightSensorsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('LightSensorsApi', function() {
    describe('lightSensorsDelete', function() {
      it('should call lightSensorsDelete successfully', function(done) {
        //uncomment below and update the code to test lightSensorsDelete
        //instance.lightSensorsDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('lightSensorsDiscover', function() {
      it('should call lightSensorsDiscover successfully', function(done) {
        //uncomment below and update the code to test lightSensorsDiscover
        //instance.lightSensorsDiscover(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('lightSensorsEventPost', function() {
      it('should call lightSensorsEventPost successfully', function(done) {
        //uncomment below and update the code to test lightSensorsEventPost
        //instance.lightSensorsEventPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('lightSensorsGet', function() {
      it('should call lightSensorsGet successfully', function(done) {
        //uncomment below and update the code to test lightSensorsGet
        //instance.lightSensorsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('lightSensorsGetEvents', function() {
      it('should call lightSensorsGetEvents successfully', function(done) {
        //uncomment below and update the code to test lightSensorsGetEvents
        //instance.lightSensorsGetEvents(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('lightSensorsGetLightSensor', function() {
      it('should call lightSensorsGetLightSensor successfully', function(done) {
        //uncomment below and update the code to test lightSensorsGetLightSensor
        //instance.lightSensorsGetLightSensor(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('lightSensorsPost', function() {
      it('should call lightSensorsPost successfully', function(done) {
        //uncomment below and update the code to test lightSensorsPost
        //instance.lightSensorsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('lightSensorsPut', function() {
      it('should call lightSensorsPut successfully', function(done) {
        //uncomment below and update the code to test lightSensorsPut
        //instance.lightSensorsPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
