/**
 * Gateway Software API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GatewaySoftwareApi);
  }
}(this, function(expect, GatewaySoftwareApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GatewaySoftwareApi.NetworkNodesApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('NetworkNodesApi', function() {
    describe('networkNodesDelete', function() {
      it('should call networkNodesDelete successfully', function(done) {
        //uncomment below and update the code to test networkNodesDelete
        //instance.networkNodesDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('networkNodesDeleteAll', function() {
      it('should call networkNodesDeleteAll successfully', function(done) {
        //uncomment below and update the code to test networkNodesDeleteAll
        //instance.networkNodesDeleteAll(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('networkNodesDiscover', function() {
      it('should call networkNodesDiscover successfully', function(done) {
        //uncomment below and update the code to test networkNodesDiscover
        //instance.networkNodesDiscover(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('networkNodesGet', function() {
      it('should call networkNodesGet successfully', function(done) {
        //uncomment below and update the code to test networkNodesGet
        //instance.networkNodesGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('networkNodesGetDeviceNodes', function() {
      it('should call networkNodesGetDeviceNodes successfully', function(done) {
        //uncomment below and update the code to test networkNodesGetDeviceNodes
        //instance.networkNodesGetDeviceNodes(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('networkNodesGetDevices', function() {
      it('should call networkNodesGetDevices successfully', function(done) {
        //uncomment below and update the code to test networkNodesGetDevices
        //instance.networkNodesGetDevices(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('networkNodesGetNode', function() {
      it('should call networkNodesGetNode successfully', function(done) {
        //uncomment below and update the code to test networkNodesGetNode
        //instance.networkNodesGetNode(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('networkNodesPost', function() {
      it('should call networkNodesPost successfully', function(done) {
        //uncomment below and update the code to test networkNodesPost
        //instance.networkNodesPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('networkNodesPut', function() {
      it('should call networkNodesPut successfully', function(done) {
        //uncomment below and update the code to test networkNodesPut
        //instance.networkNodesPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
