/**
 * Gateway Software API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GatewaySoftwareApi);
  }
}(this, function(expect, GatewaySoftwareApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GatewaySoftwareApi.LightSensorDto();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('LightSensorDto', function() {
    it('should create an instance of LightSensorDto', function() {
      // uncomment below and update the code to test LightSensorDto
      //var instane = new GatewaySoftwareApi.LightSensorDto();
      //expect(instance).to.be.a(GatewaySoftwareApi.LightSensorDto);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new GatewaySoftwareApi.LightSensorDto();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new GatewaySoftwareApi.LightSensorDto();
      //expect(instance).to.be();
    });

    it('should have the property protocol (base name: "protocol")', function() {
      // uncomment below and update the code to test the property protocol
      //var instane = new GatewaySoftwareApi.LightSensorDto();
      //expect(instance).to.be();
    });

    it('should have the property externalId (base name: "externalId")', function() {
      // uncomment below and update the code to test the property externalId
      //var instane = new GatewaySoftwareApi.LightSensorDto();
      //expect(instance).to.be();
    });

    it('should have the property discoveredDate (base name: "discoveredDate")', function() {
      // uncomment below and update the code to test the property discoveredDate
      //var instane = new GatewaySoftwareApi.LightSensorDto();
      //expect(instance).to.be();
    });

    it('should have the property isOnline (base name: "isOnline")', function() {
      // uncomment below and update the code to test the property isOnline
      //var instane = new GatewaySoftwareApi.LightSensorDto();
      //expect(instance).to.be();
    });

    it('should have the property minSensorLevel (base name: "minSensorLevel")', function() {
      // uncomment below and update the code to test the property minSensorLevel
      //var instane = new GatewaySoftwareApi.LightSensorDto();
      //expect(instance).to.be();
    });

    it('should have the property maxSensorLevel (base name: "maxSensorLevel")', function() {
      // uncomment below and update the code to test the property maxSensorLevel
      //var instane = new GatewaySoftwareApi.LightSensorDto();
      //expect(instance).to.be();
    });

    it('should have the property minIlluminance (base name: "minIlluminance")', function() {
      // uncomment below and update the code to test the property minIlluminance
      //var instane = new GatewaySoftwareApi.LightSensorDto();
      //expect(instance).to.be();
    });

    it('should have the property maxIlluminance (base name: "maxIlluminance")', function() {
      // uncomment below and update the code to test the property maxIlluminance
      //var instane = new GatewaySoftwareApi.LightSensorDto();
      //expect(instance).to.be();
    });

    it('should have the property sensorLevel (base name: "sensorLevel")', function() {
      // uncomment below and update the code to test the property sensorLevel
      //var instane = new GatewaySoftwareApi.LightSensorDto();
      //expect(instance).to.be();
    });

    it('should have the property illuminance (base name: "illuminance")', function() {
      // uncomment below and update the code to test the property illuminance
      //var instane = new GatewaySoftwareApi.LightSensorDto();
      //expect(instance).to.be();
    });

    it('should have the property properties (base name: "properties")', function() {
      // uncomment below and update the code to test the property properties
      //var instane = new GatewaySoftwareApi.LightSensorDto();
      //expect(instance).to.be();
    });

  });

}));
