/**
 * Gateway Software API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GatewaySoftwareApi);
  }
}(this, function(expect, GatewaySoftwareApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GatewaySoftwareApi.WebHookDto();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('WebHookDto', function() {
    it('should create an instance of WebHookDto', function() {
      // uncomment below and update the code to test WebHookDto
      //var instane = new GatewaySoftwareApi.WebHookDto();
      //expect(instance).to.be.a(GatewaySoftwareApi.WebHookDto);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new GatewaySoftwareApi.WebHookDto();
      //expect(instance).to.be();
    });

    it('should have the property domainEvents (base name: "domainEvents")', function() {
      // uncomment below and update the code to test the property domainEvents
      //var instane = new GatewaySoftwareApi.WebHookDto();
      //expect(instance).to.be();
    });

    it('should have the property callbackUrl (base name: "callbackUrl")', function() {
      // uncomment below and update the code to test the property callbackUrl
      //var instane = new GatewaySoftwareApi.WebHookDto();
      //expect(instance).to.be();
    });

    it('should have the property applicationKeyId (base name: "applicationKeyId")', function() {
      // uncomment below and update the code to test the property applicationKeyId
      //var instane = new GatewaySoftwareApi.WebHookDto();
      //expect(instance).to.be();
    });

    it('should have the property applicationKey (base name: "applicationKey")', function() {
      // uncomment below and update the code to test the property applicationKey
      //var instane = new GatewaySoftwareApi.WebHookDto();
      //expect(instance).to.be();
    });

  });

}));
