/**
 * Gateway Software API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.GatewaySoftwareApi) {
      root.GatewaySoftwareApi = {};
    }
    root.GatewaySoftwareApi.CreateLightDto = factory(root.GatewaySoftwareApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The CreateLightDto model module.
   * @module model/CreateLightDto
   * @version v1
   */

  /**
   * Constructs a new <code>CreateLightDto</code>.
   * The light
   * @alias module:model/CreateLightDto
   * @class
   * @param externalId {String} The external system's ID for this light
   * @param lightType {String} The type of light (Individual, Tunable, Rgb)
   * @param minLevel {Number} The minimum light level (0-10000)
   * @param maxLevel {Number} The maximum light level (0-10000)
   * @param name {String} The device name
   */
  var exports = function(externalId, lightType, minLevel, maxLevel, name) {
    var _this = this;

    _this['externalId'] = externalId;
    _this['lightType'] = lightType;


    _this['minLevel'] = minLevel;
    _this['maxLevel'] = maxLevel;
    _this['name'] = name;

  };

  /**
   * Constructs a <code>CreateLightDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreateLightDto} obj Optional instance to populate.
   * @return {module:model/CreateLightDto} The populated <code>CreateLightDto</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('externalId')) {
        obj['externalId'] = ApiClient.convertToType(data['externalId'], 'String');
      }
      if (data.hasOwnProperty('lightType')) {
        obj['lightType'] = ApiClient.convertToType(data['lightType'], 'String');
      }
      if (data.hasOwnProperty('minimumKelvin')) {
        obj['minimumKelvin'] = ApiClient.convertToType(data['minimumKelvin'], 'Number');
      }
      if (data.hasOwnProperty('maximumKelvin')) {
        obj['maximumKelvin'] = ApiClient.convertToType(data['maximumKelvin'], 'Number');
      }
      if (data.hasOwnProperty('minLevel')) {
        obj['minLevel'] = ApiClient.convertToType(data['minLevel'], 'Number');
      }
      if (data.hasOwnProperty('maxLevel')) {
        obj['maxLevel'] = ApiClient.convertToType(data['maxLevel'], 'Number');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('properties')) {
        obj['properties'] = ApiClient.convertToType(data['properties'], 'String');
      }
    }
    return obj;
  }

  /**
   * The external system's ID for this light
   * @member {String} externalId
   */
  exports.prototype['externalId'] = undefined;
  /**
   * The type of light (Individual, Tunable, Rgb)
   * @member {String} lightType
   */
  exports.prototype['lightType'] = undefined;
  /**
   * The minimum Kelvin value of the light or null
   * @member {Number} minimumKelvin
   */
  exports.prototype['minimumKelvin'] = undefined;
  /**
   * The maximum Kelvin value of the light or null
   * @member {Number} maximumKelvin
   */
  exports.prototype['maximumKelvin'] = undefined;
  /**
   * The minimum light level (0-10000)
   * @member {Number} minLevel
   */
  exports.prototype['minLevel'] = undefined;
  /**
   * The maximum light level (0-10000)
   * @member {Number} maxLevel
   */
  exports.prototype['maxLevel'] = undefined;
  /**
   * The device name
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * The external system's device properties
   * @member {String} properties
   */
  exports.prototype['properties'] = undefined;



  return exports;
}));


