/**
 * Gateway Software API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.GatewaySoftwareApi) {
      root.GatewaySoftwareApi = {};
    }
    root.GatewaySoftwareApi.CreateActionDto = factory(root.GatewaySoftwareApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The CreateActionDto model module.
   * @module model/CreateActionDto
   * @version v1
   */

  /**
   * Constructs a new <code>CreateActionDto</code>.
   * The action
   * @alias module:model/CreateActionDto
   * @class
   * @param type {module:model/CreateActionDto.TypeEnum} The action type
   * @param spaceId {Number} The space ID
   * @param level {Number} The level
   */
  var exports = function(type, spaceId, level) {
    var _this = this;

    _this['type'] = type;
    _this['spaceId'] = spaceId;
    _this['level'] = level;
  };

  /**
   * Constructs a <code>CreateActionDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreateActionDto} obj Optional instance to populate.
   * @return {module:model/CreateActionDto} The populated <code>CreateActionDto</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
      if (data.hasOwnProperty('spaceId')) {
        obj['spaceId'] = ApiClient.convertToType(data['spaceId'], 'Number');
      }
      if (data.hasOwnProperty('level')) {
        obj['level'] = ApiClient.convertToType(data['level'], 'Number');
      }
    }
    return obj;
  }

  /**
   * The action type
   * @member {module:model/CreateActionDto.TypeEnum} type
   */
  exports.prototype['type'] = undefined;
  /**
   * The space ID
   * @member {Number} spaceId
   */
  exports.prototype['spaceId'] = undefined;
  /**
   * The level
   * @member {Number} level
   */
  exports.prototype['level'] = undefined;


  /**
   * Allowed values for the <code>type</code> property.
   * @enum {String}
   * @readonly
   */
  exports.TypeEnum = {
    /**
     * value: "TurnOff"
     * @const
     */
    "TurnOff": "TurnOff",
    /**
     * value: "TurnOn"
     * @const
     */
    "TurnOn": "TurnOn",
    /**
     * value: "Dim"
     * @const
     */
    "Dim": "Dim"  };


  return exports;
}));


