/**
 * Gateway Software API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.GatewaySoftwareApi) {
      root.GatewaySoftwareApi = {};
    }
    root.GatewaySoftwareApi.CreateDimmerEventDto = factory(root.GatewaySoftwareApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The CreateDimmerEventDto model module.
   * @module model/CreateDimmerEventDto
   * @version v1
   */

  /**
   * Constructs a new <code>CreateDimmerEventDto</code>.
   * @alias module:model/CreateDimmerEventDto
   * @class
   * @param level {Number} The dimmer level (0-100)
   */
  var exports = function(level) {
    var _this = this;

    _this['level'] = level;
  };

  /**
   * Constructs a <code>CreateDimmerEventDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreateDimmerEventDto} obj Optional instance to populate.
   * @return {module:model/CreateDimmerEventDto} The populated <code>CreateDimmerEventDto</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('level')) {
        obj['level'] = ApiClient.convertToType(data['level'], 'Number');
      }
    }
    return obj;
  }

  /**
   * The dimmer level (0-100)
   * @member {Number} level
   */
  exports.prototype['level'] = undefined;



  return exports;
}));


