/**
 * Gateway Software API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.GatewaySoftwareApi) {
      root.GatewaySoftwareApi = {};
    }
    root.GatewaySoftwareApi.DashboardDeviceStatusByDeviceTypeDto = factory(root.GatewaySoftwareApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The DashboardDeviceStatusByDeviceTypeDto model module.
   * @module model/DashboardDeviceStatusByDeviceTypeDto
   * @version v1
   */

  /**
   * Constructs a new <code>DashboardDeviceStatusByDeviceTypeDto</code>.
   * @alias module:model/DashboardDeviceStatusByDeviceTypeDto
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>DashboardDeviceStatusByDeviceTypeDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DashboardDeviceStatusByDeviceTypeDto} obj Optional instance to populate.
   * @return {module:model/DashboardDeviceStatusByDeviceTypeDto} The populated <code>DashboardDeviceStatusByDeviceTypeDto</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('deviceType')) {
        obj['deviceType'] = ApiClient.convertToType(data['deviceType'], 'String');
      }
      if (data.hasOwnProperty('deviceTypeSingular')) {
        obj['deviceTypeSingular'] = ApiClient.convertToType(data['deviceTypeSingular'], 'String');
      }
      if (data.hasOwnProperty('onlineCount')) {
        obj['onlineCount'] = ApiClient.convertToType(data['onlineCount'], 'Number');
      }
      if (data.hasOwnProperty('offlineCount')) {
        obj['offlineCount'] = ApiClient.convertToType(data['offlineCount'], 'Number');
      }
      if (data.hasOwnProperty('total')) {
        obj['total'] = ApiClient.convertToType(data['total'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {String} deviceType
   */
  exports.prototype['deviceType'] = undefined;
  /**
   * @member {String} deviceTypeSingular
   */
  exports.prototype['deviceTypeSingular'] = undefined;
  /**
   * @member {Number} onlineCount
   */
  exports.prototype['onlineCount'] = undefined;
  /**
   * @member {Number} offlineCount
   */
  exports.prototype['offlineCount'] = undefined;
  /**
   * @member {Number} total
   */
  exports.prototype['total'] = undefined;



  return exports;
}));


