/**
 * Gateway Software API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.GatewaySoftwareApi) {
      root.GatewaySoftwareApi = {};
    }
    root.GatewaySoftwareApi.DecoderFallback = factory(root.GatewaySoftwareApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The DecoderFallback model module.
   * @module model/DecoderFallback
   * @version v1
   */

  /**
   * Constructs a new <code>DecoderFallback</code>.
   * @alias module:model/DecoderFallback
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>DecoderFallback</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DecoderFallback} obj Optional instance to populate.
   * @return {module:model/DecoderFallback} The populated <code>DecoderFallback</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('maxCharCount')) {
        obj['maxCharCount'] = ApiClient.convertToType(data['maxCharCount'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Number} maxCharCount
   */
  exports.prototype['maxCharCount'] = undefined;



  return exports;
}));


