/**
 * Gateway Software API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.GatewaySoftwareApi) {
      root.GatewaySoftwareApi = {};
    }
    root.GatewaySoftwareApi.LightDto = factory(root.GatewaySoftwareApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The LightDto model module.
   * @module model/LightDto
   * @version v1
   */

  /**
   * Constructs a new <code>LightDto</code>.
   * @alias module:model/LightDto
   * @class
   * @param name {String} 
   */
  var exports = function(name) {
    var _this = this;


    _this['name'] = name;















  };

  /**
   * Constructs a <code>LightDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LightDto} obj Optional instance to populate.
   * @return {module:model/LightDto} The populated <code>LightDto</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('protocol')) {
        obj['protocol'] = ApiClient.convertToType(data['protocol'], 'String');
      }
      if (data.hasOwnProperty('externalId')) {
        obj['externalId'] = ApiClient.convertToType(data['externalId'], 'String');
      }
      if (data.hasOwnProperty('discoveredDate')) {
        obj['discoveredDate'] = ApiClient.convertToType(data['discoveredDate'], 'Date');
      }
      if (data.hasOwnProperty('isOnline')) {
        obj['isOnline'] = ApiClient.convertToType(data['isOnline'], 'Boolean');
      }
      if (data.hasOwnProperty('level')) {
        obj['level'] = ApiClient.convertToType(data['level'], 'Number');
      }
      if (data.hasOwnProperty('minLevel')) {
        obj['minLevel'] = ApiClient.convertToType(data['minLevel'], 'Number');
      }
      if (data.hasOwnProperty('maxLevel')) {
        obj['maxLevel'] = ApiClient.convertToType(data['maxLevel'], 'Number');
      }
      if (data.hasOwnProperty('isEmergency')) {
        obj['isEmergency'] = ApiClient.convertToType(data['isEmergency'], 'Boolean');
      }
      if (data.hasOwnProperty('emergencyTimeout')) {
        obj['emergencyTimeout'] = ApiClient.convertToType(data['emergencyTimeout'], 'Number');
      }
      if (data.hasOwnProperty('emergencyLightLevel')) {
        obj['emergencyLightLevel'] = ApiClient.convertToType(data['emergencyLightLevel'], 'Number');
      }
      if (data.hasOwnProperty('lightType')) {
        obj['lightType'] = ApiClient.convertToType(data['lightType'], 'String');
      }
      if (data.hasOwnProperty('minimumKelvin')) {
        obj['minimumKelvin'] = ApiClient.convertToType(data['minimumKelvin'], 'Number');
      }
      if (data.hasOwnProperty('maximumKelvin')) {
        obj['maximumKelvin'] = ApiClient.convertToType(data['maximumKelvin'], 'Number');
      }
      if (data.hasOwnProperty('kelvin')) {
        obj['kelvin'] = ApiClient.convertToType(data['kelvin'], 'Number');
      }
      if (data.hasOwnProperty('properties')) {
        obj['properties'] = ApiClient.convertToType(data['properties'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {String} protocol
   */
  exports.prototype['protocol'] = undefined;
  /**
   * @member {String} externalId
   */
  exports.prototype['externalId'] = undefined;
  /**
   * @member {Date} discoveredDate
   */
  exports.prototype['discoveredDate'] = undefined;
  /**
   * @member {Boolean} isOnline
   */
  exports.prototype['isOnline'] = undefined;
  /**
   * The current light level.
   * @member {Number} level
   */
  exports.prototype['level'] = undefined;
  /**
   * @member {Number} minLevel
   */
  exports.prototype['minLevel'] = undefined;
  /**
   * @member {Number} maxLevel
   */
  exports.prototype['maxLevel'] = undefined;
  /**
   * @member {Boolean} isEmergency
   */
  exports.prototype['isEmergency'] = undefined;
  /**
   * @member {Number} emergencyTimeout
   */
  exports.prototype['emergencyTimeout'] = undefined;
  /**
   * @member {Number} emergencyLightLevel
   */
  exports.prototype['emergencyLightLevel'] = undefined;
  /**
   * @member {String} lightType
   */
  exports.prototype['lightType'] = undefined;
  /**
   * @member {Number} minimumKelvin
   */
  exports.prototype['minimumKelvin'] = undefined;
  /**
   * @member {Number} maximumKelvin
   */
  exports.prototype['maximumKelvin'] = undefined;
  /**
   * @member {Number} kelvin
   */
  exports.prototype['kelvin'] = undefined;
  /**
   * @member {String} properties
   */
  exports.prototype['properties'] = undefined;



  return exports;
}));


