/**
 * Gateway Software API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.GatewaySoftwareApi) {
      root.GatewaySoftwareApi = {};
    }
    root.GatewaySoftwareApi.PolicyDto = factory(root.GatewaySoftwareApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The PolicyDto model module.
   * @module model/PolicyDto
   * @version v1
   */

  /**
   * Constructs a new <code>PolicyDto</code>.
   * @alias module:model/PolicyDto
   * @class
   */
  var exports = function() {
    var _this = this;








  };

  /**
   * Constructs a <code>PolicyDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PolicyDto} obj Optional instance to populate.
   * @return {module:model/PolicyDto} The populated <code>PolicyDto</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
      if (data.hasOwnProperty('minimumLightLevel')) {
        obj['minimumLightLevel'] = ApiClient.convertToType(data['minimumLightLevel'], 'Number');
      }
      if (data.hasOwnProperty('maximumLightLevel')) {
        obj['maximumLightLevel'] = ApiClient.convertToType(data['maximumLightLevel'], 'Number');
      }
      if (data.hasOwnProperty('occupancyTimeout')) {
        obj['occupancyTimeout'] = ApiClient.convertToType(data['occupancyTimeout'], 'Number');
      }
      if (data.hasOwnProperty('spaceTypeId')) {
        obj['spaceTypeId'] = ApiClient.convertToType(data['spaceTypeId'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {String} type
   */
  exports.prototype['type'] = undefined;
  /**
   * @member {Number} minimumLightLevel
   */
  exports.prototype['minimumLightLevel'] = undefined;
  /**
   * @member {Number} maximumLightLevel
   */
  exports.prototype['maximumLightLevel'] = undefined;
  /**
   * @member {Number} occupancyTimeout
   */
  exports.prototype['occupancyTimeout'] = undefined;
  /**
   * @member {Number} spaceTypeId
   */
  exports.prototype['spaceTypeId'] = undefined;



  return exports;
}));


