/**
 * Gateway Software API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.GatewaySoftwareApi) {
      root.GatewaySoftwareApi = {};
    }
    root.GatewaySoftwareApi.UpdateSpaceDto = factory(root.GatewaySoftwareApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The UpdateSpaceDto model module.
   * @module model/UpdateSpaceDto
   * @version v1
   */

  /**
   * Constructs a new <code>UpdateSpaceDto</code>.
   * The space
   * @alias module:model/UpdateSpaceDto
   * @class
   * @param name {String} The space name
   * @param mode {module:model/UpdateSpaceDto.ModeEnum} The space mode
   */
  var exports = function(name, mode) {
    var _this = this;

    _this['name'] = name;
    _this['mode'] = mode;
  };

  /**
   * Constructs a <code>UpdateSpaceDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UpdateSpaceDto} obj Optional instance to populate.
   * @return {module:model/UpdateSpaceDto} The populated <code>UpdateSpaceDto</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('mode')) {
        obj['mode'] = ApiClient.convertToType(data['mode'], 'String');
      }
    }
    return obj;
  }

  /**
   * The space name
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * The space mode
   * @member {module:model/UpdateSpaceDto.ModeEnum} mode
   */
  exports.prototype['mode'] = undefined;


  /**
   * Allowed values for the <code>mode</code> property.
   * @enum {String}
   * @readonly
   */
  exports.ModeEnum = {
    /**
     * value: "Occupancy"
     * @const
     */
    "Occupancy": "Occupancy",
    /**
     * value: "Vacancy"
     * @const
     */
    "Vacancy": "Vacancy"  };


  return exports;
}));


